# add_newline = false

[battery]
format = "[$symbol$percentage]($style) "
discharging_symbol = "âš¡ï¸"
charging_symbol = "ğŸ”Œ"
unknown_symbol = "ğŸ”Œ"
full_symbol = ""
empty_symbol = "âš¡ï¸"

[[battery.display]]
threshold = 15

[character]
success_symbol = "[â¯](bold fg:#e0dac9)"
vicmd_symbol = "[â–ª](bold fg:#b58900)"
error_symbol = "[âœ–](bold red)"

[directory]
style = "bold fg:#e0dac9"

[hostname]
ssh_only = false
format =  "@[$hostname]($style): "
style = "fg:#e0dac9"

[username]
show_always = true
format = "[$user](fg:#e0dac9)"

[git_status]
disabled = true

[python]
format = '(in [$virtualenv]($style))'

[scala]
disabled = true

[package]
disabled = true
