add_newline = false

[battery]
format = "[$symbol$percentage]($style) "
discharging_symbol = "âš¡ï¸"
charging_symbol = "ğŸ”Œ"
unknown_symbol = "ğŸ”Œ"
full_symbol = ""
empty_symbol = "âš¡ï¸"

[[battery.display]]
threshold = 15
style = "bold red"

[character]
vicmd_symbol = "[â–ª](bold yellow)"
error_symbol = "[âœ–](bold red)"

[hostname]
ssh_only = false
format =  "@[$hostname]($style): "

[username]
show_always = true
format =  "[$user]($style)"
